import { categoryMeta } from "@/lib/categoryStyles";
import type { CheckinDTO } from "@/lib/types";

interface CheckinCardProps {
  checkin: CheckinDTO;
}

export default function CheckinCard({ checkin }: CheckinCardProps) {
  return (
    <div className="flex flex-col gap-5 rounded-3xl border border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-teal-50 p-6 shadow-sm shadow-emerald-900/5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-xl">💬</span>
          <h3 className="text-lg font-semibold text-emerald-900">Your weekly check-in</h3>
        </div>
        <span className="text-xs text-emerald-600">
          {new Date(checkin.generatedAt).toLocaleString()}
        </span>
      </div>

      <p className="text-[15px] leading-relaxed text-slate-800">{checkin.aiSummary}</p>

      {checkin.topCategories.length > 0 && (
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-sm font-medium text-slate-500">Worth watching:</span>
          {checkin.topCategories.map((c) => {
            const meta = categoryMeta(c);
            return (
              <span
                key={c}
                className={`flex items-center gap-1 rounded-full px-3 py-1 text-xs font-semibold ${meta.badgeBg} ${meta.badgeText}`}
              >
                {meta.emoji} {c}
              </span>
            );
          })}
        </div>
      )}

      {checkin.tips.length > 0 && (
        <div className="flex flex-col gap-2">
          <p className="text-sm font-medium text-slate-500">A few ideas:</p>
          <ul className="flex flex-col gap-2">
            {checkin.tips.map((tip, i) => (
              <li
                key={i}
                className="flex gap-2.5 rounded-xl bg-white/70 px-3 py-2 text-sm text-slate-800 ring-1 ring-slate-100"
              >
                <span className="shrink-0 font-semibold text-emerald-600">{i + 1}.</span>
                {tip}
              </li>
            ))}
          </ul>
        </div>
      )}

      <p className="text-xs text-slate-400">
        Generated by {checkin.model} · total spend this period: ${checkin.totalSpend.toFixed(2)}
      </p>
    </div>
  );
}
